title: vyos-pkg
email: matthew@kobayashi.au
description: >-
  An unofficial Debian package repository for VyOS-specific packages
url: https://mattkobayashi.github.io
baseurl: /vyos-pkg/
github_username: MattKobayashi

# Build settings
theme: minima
plugins:
  - jekyll-feed
exclude:
  - tools/
  - doc/
  - renovate.json
