---
title: vyos-pkg
email: matthew@tech.bymatt.au
description: >-
  An unofficial Debian package repository of VyOS packages
url: https://techbymatt.github.io
baseurl: /vyos-pkg/
github_username: techbymatt

# Build settings
theme: minima
plugins:
  - jekyll-feed
exclude:
  - tools/
  - doc/
  - renovate.json
