title: vyos-pkg-circinus
email: matthew@kobayashi.au
description: >-
  An unofficial Debian package repository for VyOS-specific packages
baseurl: "/circinus"
url: "https://mattkobayashi.github.io/vyos-pkg"
github_username: MattKobayashi

# Build settings
theme: minima
plugins:
  - jekyll-feed
exclude:
  - tools/
  - doc/
