---
name: "Build TBM VyOS Package Repository"

on:
  workflow_dispatch:

jobs:
  build-packages:
    container:
      env:
        TZ: Australia/Brisbane
      image: vyos/vyos-build:${{ matrix.branch }}
    name: Build packages
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout the `vyos-pkg` repository
        uses: actions/checkout@v4.2.2
      - name: Checkout the `vyos-build` repository
        uses: actions/checkout@v4.2.2
        with:
          path: vyos-build
          ref: ${{ matrix.branch }}
          repository: vyos/vyos-build
      - name: Build the packages
        working-directory: vyos-build/scripts/package-build
        run: |
          set -eux
          cp ${{ github.workspace }}/vyos-build/packages/${{ matrix.branch }}/package.toml .
          ./build.py
      - name: Upload the .deb files as artifacts
        uses: actions/upload-artifact@v4.4.3
        with:
          name: vyos-packages-${{ matrix.branch }}
          path: vyos-build/scripts/package-build/${{ matrix.branch }}/*.deb
    strategy:
      fail-fast: false
      matrix:
        branch:
          - current
  create-repo:
    name: Create .deb repository
    needs: build-packages
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout the `vyos-pkg` repository
        uses: actions/checkout@v4.2.2
      - name: Download the .deb file artifacts
        uses: actions/download-artifact@v4.1.8
        with:
          name: vyos-packages-current
          path: packages/current
      - name: Install required packages
        run: |
          set -eux
          until sudo apt-get update
          do
            sleep 1
          done
          sudo apt-get install --yes \
            jq \
            createrepo-c \
            coreutils \
            gnupg2 \
            dpkg-dev
      - name: Insert environment variables
        run: |
          set -eux
          echo GNUPGHOME="$(mktemp -d /tmp/pgpkeys-XXXXXX)" >> $GITHUB_ENV
          echo REPO_OWNER="$(echo ${GITHUB_REPOSITORY} | cut -d/ -f1)" >> $GITHUB_ENV
          echo REPO_NAME="$(echo ${GITHUB_REPOSITORY} | cut -d/ -f2)" >> $GITHUB_ENV
      - id: import_gpg
        name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v6.2.0
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}
      - name: Confirm GPG key is loaded
        run: |
          set -eux
          gpg --list-keys | grep $(echo "${{ steps.import_gpg.outputs.fingerprint }}")
      - name: Setup Pages
        uses: actions/configure-pages@v5.0.0
      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@v1.0.13
        with:
          source: ./
          destination: ./_site
      - name: Build .deb repository
        run: |
          set -eux
          export GPG_FINGERPRINT="${{ steps.import_gpg.outputs.fingerprint }}"
          export ORIGIN="${{ steps.import_gpg.outputs.name }}"
          scripts/build_repo.sh
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3.0.1
      - id: deployment
        name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4.0.5
