---
name: 'Build package'

on:
  workflow_call:

jobs:
  build-package:
    name: 'Build package'
    runs-on: self-hosted
    container:
      image: vyos/vyos-build:current
      env:
        TZ: Australia/Brisbane
      options: '--privileged --sysctl net.ipv6.conf.lo.disable_ipv6=0'
    steps:
      - name: 'Checkout the `vyos-pkg` repository'
        run: |
          set -eux
          rm -rf vyos-pkg/
          git clone --depth 1 https://github.com/MattKobayashi/vyos-pkg.git
      - name: 'Checkout the `vyos-build` repository'
        run: |
          set -eux
          rm -rf vyos-build/
          git clone --depth 1 https://github.com/vyos/vyos-build.git
      - name: 'Get build info'
        id: build-info
        working-directory: vyos-build/packages/ethtool
        run: |
          set -eux
          echo commit-id=$(awk -F "[\'-,:; ]+" '/scmCommit/ { print $3 }' Jenkinsfile | sed -En '1p') >> "$GITHUB_OUTPUT"
      - name: 'Checkout the upstream repository'
        working-directory: vyos-build/packages/ethtool
        run: |
          set -eux
          git clone https://salsa.debian.org/kernel-team/ethtool.git ethtool
          cd ethtool
          git reset --hard ${{ steps.build-info.outputs.commit-id }}
      - name: 'Build the .deb files'
        working-directory: vyos-build/packages/ethtool/ethtool
        run: |
          set -eux
          sudo mk-build-deps --install --tool "apt-get --yes --no-install-recommends"
          dpkg-buildpackage -uc -us -tc -b
      - name: 'Commit the .deb files to the `vyos-pkg` repository'
        working-directory: vyos-pkg
        run: |
          set -eux
          find packages/ -name 'ethtool*.deb' -exec git rm {} \;
          mv ../vyos-build/packages/ethtool/*.deb packages/
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add packages/*
          git commit -m "ethtool"
          git push -u https://MattKobayashi:${{ secrets.GITHUB_TOKEN }}@github.com/MattKobayashi/vyos-pkg.git
