---
name: 'Build package'

on:
  workflow_call:
    inputs:
      job-name:
        required: true
        type: string

jobs:
  build-package:
    name: 'Build package'
    runs-on: self-hosted
    container:
      image: vyos/vyos-build:current
      env:
        TZ: Australia/Brisbane
      options: '--privileged --sysctl net.ipv6.conf.lo.disable_ipv6=0'
    steps:
      - name: 'Checkout the `vyos-pkg` repository'
        run: |
          set -eux
          rm -rf vyos-pkg/
          git clone --depth 1 https://github.com/MattKobayashi/vyos-pkg.git
      - name: 'Checkout the `vyos-build` repository'
        run: |
          set -eux
          rm -rf vyos-build/
          git clone --depth 1 https://github.com/vyos/vyos-build.git
      - name: 'Build the package(s)'
        working-directory: vyos-build/packages/${{ inputs.job-name }}
        run: |
          set -eux
          pip3 install --break-system-packages json-repair
          python3 ../../../vyos-pkg/.github/scripts/parse_jf.py
      - name: 'Remove old .deb files from the `vyos-pkg` repository'
        working-directory: vyos-pkg
        run: |
          set -eux
          find packages/current/ -name 'libyang*.deb' -exec git rm {} \;
          find packages/current/ -name 'librtr*.deb' -exec git rm {} \;
          find packages/current/ -name 'frr*.deb' -exec git rm {} \;
          find packages/current/ -name 'rtr-tools*.deb' -exec git rm {} \;
      - name: 'Commit the new .deb files to the `vyos-pkg` repository'
        working-directory: vyos-pkg
        run: |
          set -eux
          mv ../vyos-build/packages/${{ inputs.job-name }}/*.deb packages/current/
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add packages/*
          git diff-index --quiet HEAD || git commit -m "${{ inputs.job-name }}"
          git push -u https://MattKobayashi:${{ secrets.GITHUB_TOKEN }}@github.com/MattKobayashi/vyos-pkg.git
