---
name: 'Build package'

on:
  workflow_call:

jobs:
  build-package:
    name: 'Build package'
    runs-on: self-hosted
    container:
      image: vyos/vyos-build:current
      env:
        TZ: Australia/Brisbane
      options: '--privileged --sysctl net.ipv6.conf.lo.disable_ipv6=0'
    steps:
      - name: 'Checkout the `vyos-pkg` repository'
        run: |
          set -eux
          rm -rf vyos-pkg/
          git clone --depth 1 https://github.com/MattKobayashi/vyos-pkg.git
      - name: 'Checkout the `vyos-build` repository'
        run: |
          set -eux
          rm -rf vyos-build/
          git clone --depth 1 https://github.com/vyos/vyos-build.git
      - name: 'Execute parse_jf.py'
        working-directory: vyos-build/packages/hostap
        run: |
          set -eux
          pip3 install --break-system-packages json-repair
          python3 ../../../vyos-pkg/.github/scripts/parse_jf.py
      - name: 'Commit the .deb files to the `vyos-pkg` repository'
        working-directory: vyos-pkg
        run: |
          set -eux
          find packages/current/ -name 'eapoltest*.deb' -exec git rm {} \;
          find packages/current/ -name 'hostapd*.deb' -exec git rm {} \;
          find packages/current/ -name 'libwpa*.deb' -exec git rm {} \;
          find packages/current/ -name 'wpasupplicant*.deb' -exec git rm {} \;
          mv ../vyos-build/packages/hostap/*.deb packages/current/
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add packages/*
          git commit -m "hostap"
          git push -u https://MattKobayashi:${{ secrets.GITHUB_TOKEN }}@github.com/MattKobayashi/vyos-pkg.git
