---
jobs:
  build:
    container:
      env:
        TZ: Australia/Brisbane
      image: ghcr.io/techbymatt/vyos-build:rolling
      options: "--privileged --sysctl net.ipv6.conf.lo.disable_ipv6=0"
    defaults:
      run:
        shell: bash
    name: Build (container)
    permissions:
      packages: read
    runs-on:
      group: ${{ matrix.runner_group }}
      labels: ${{ matrix.runner_label }}
    steps:
      # - name: Random delay (0-5 minutes)
      #   env:
      #     MIN_DELAY: 0
      #     MAX_DELAY: 300
      #   run: |
      #     DELAY=$((MIN_DELAY + RANDOM % (MAX_DELAY - MIN_DELAY + 1)))
      #     echo "Sleeping for $DELAY seconds..."
      #     sleep $DELAY
      - name: Checkout the vyos-build repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          path: vyos-build
          ref: rolling
          repository: vyos/vyos-build
      - name: Setup golang
        uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6.4.0
        with:
          go-version: "1.26.4"
      - name: Build the packages
        run: |
          PACKAGES=(
            amazon-cloudwatch-agent
            amazon-ssm-agent
            aws-gwlbtun
            bash-completion
            blackbox_exporter
            ddclient
            dropbear
            ethtool
            frr
            frr_exporter
            hostap
            hsflowd
            isc-dhcp
            isc-kea
            keepalived
            libnss-mapuser
            libpam-radius-auth
            linux-kernel
            ndppd
            net-snmp
            netfilter
            node_exporter
            openvpn-otp
            podman
            pyhumps
            radvd
            salt
            strongswan
            tacacs
            telegraf
            udp-broadcast-relay
            unionfs-fuse
            vpp
            vyos-1x
            waagent
            wide-dhcpv6
            xen-guest-agent
            zerotier-one
          )

          cd vyos-build/scripts/package-build
          printf "%s\n" "${PACKAGES[@]}" | xargs -n1 -P0 -I {} bash -c 'echo "Starting build for {}"; cd "{}" && python3 build.py'
      - name: Upload the .deb files as artifacts
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          if-no-files-found: error
          name: packages-build-${{ matrix.arch }}
          path: vyos-build/scripts/package-build/*/*.deb
    strategy:
      fail-fast: false
      matrix:
        arch: [amd64, arm64]
        include:
          - arch: amd64
            runner_group: tbm-vyos
            runner_label: ubuntu-24.04-64core
          - arch: arm64
            runner_group: tbm-vyos
            runner_label: ubuntu-24.04-32core-arm
    timeout-minutes: 180
  build-nocontainer:
    name: Build (no container)
    runs-on: ${{ matrix.runner_label }}
    steps:
      - name: Install dependencies
        run: |
          set -eux
          python3 -m pip install toml
          sudo apt-get update
          sudo apt-get --no-install-recommends --yes install \
            devscripts \
            equivs \
            python3-toml \
            python3-tomli
      - name: Checkout the vyos-build repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          path: vyos-build
          ref: rolling
          repository: vyos/vyos-build
      - name: Setup golang
        uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6.4.0
        with:
          go-version: "1.26.4"
      - name: Build the packages
        run: |
          PACKAGES=(
            owamp
          )

          cd vyos-build/scripts/package-build
          printf "%s\n" "${PACKAGES[@]}" | xargs -n1 -P0 -I {} bash -c 'echo "Starting build for {}"; cd "{}" && python3 build.py'
        timeout-minutes: 120
      - name: Upload the .deb files as artifacts
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          if-no-files-found: error
          name: packages-build-nocontainer-${{ matrix.arch }}
          path: vyos-build/scripts/package-build/*/*.deb
    strategy:
      fail-fast: false
      matrix:
        arch: [amd64, arm64]
        include:
          - arch: amd64
            runner_label: ubuntu-latest
          - arch: arm64
            runner_label: ubuntu-24.04-arm
    timeout-minutes: 150
  publish:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    name: Publish
    needs:
      - build
      - build-nocontainer
    permissions:
      id-token: write
      pages: write
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout the vyos-pkg repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - name: Download the .deb file artifacts
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          merge-multiple: true
          path: packages/rolling
      - name: Install required packages
        run: |
          set -eux
          sudo apt-get update
          sudo apt-get --no-install-recommends --yes install \
            jq \
            createrepo-c \
            coreutils \
            gnupg2 \
            dpkg-dev
      - name: Insert environment variables
        run: |
          set -eux
          {
            echo GNUPGHOME="$(mktemp -d /tmp/pgpkeys-XXXXXX)"
            echo REPO_OWNER="$(echo "${GITHUB_REPOSITORY}" | cut -d/ -f1)"
            echo REPO_NAME="$(echo "${GITHUB_REPOSITORY}" | cut -d/ -f2)"
          } >> "$GITHUB_ENV"
      - id: import_gpg
        name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@2dc316deee8e90f13e1a351ab510b4d5bc0c82cd # v7.0.0
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}
      - name: Confirm GPG key is loaded
        run: |
          set -eux
          gpg --list-keys | grep "${{ steps.import_gpg.outputs.fingerprint }}"
      - name: Setup Pages
        uses: actions/configure-pages@45bfe0192ca1faeb007ade9deae92b16b8254a0d # v6.0.0
      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@44a6e6beabd48582f863aeeb6cb2151cc1716697 # v1.0.13
      - name: Build .deb repository
        run: |
          set -eux
          export GPG_FINGERPRINT="${{ steps.import_gpg.outputs.fingerprint }}"
          export ORIGIN="${{ steps.import_gpg.outputs.name }}"
          sudo chown -R "$(whoami):$(whoami)" _site/
          scripts/build_repo.sh
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@fc324d3547104276b827a68afc52ff2a11cc49c9 # v5.0.0
      - id: deployment
        name: Deploy to GitHub Pages
        uses: actions/deploy-pages@cd2ce8fcbc39b97be8ca5fce6e763baed58fa128 # v5.0.0
    timeout-minutes: 10
name: Repository
on:
  schedule:
    - cron: "0 4 1,8,15,22,29 * *"
  workflow_dispatch:
permissions:
  contents: read
