---
# $schema: https://json.schemastore.org/github-workflow.json
jobs:
  build:
    container:
      env:
        TZ: Australia/Brisbane
      image: ghcr.io/techbymatt/vyos-build:rolling@sha256:28cf2b26069f31998a6c031def5f4f1edf92b23c07f4cd40024c94f5452e7ad2
      options: "--privileged --sysctl net.ipv6.conf.lo.disable_ipv6=0"
    defaults:
      run:
        shell: bash
    name: Build (container)
    permissions:
      packages: read
    runs-on: ${{ matrix.runner_label }}
    steps:
      - name: Generate GitHub App token
        id: app-token
        uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3.2.0
        with:
          client-id: ${{ secrets.APP_CLIENT_ID }}
          owner: techbymatt
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
      - id: checkout
        name: Checkout the tbm-vyos-patch repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0
          repository: techbymatt/tbm-vyos-patch
          submodules: recursive
          token: ${{ steps.app-token.outputs.token }}
      - id: patch_vyos_build
        name: Patch vyos-build
        run: |
          cp --verbose ../patches/vyos-build/*.patch .
          git apply --3way --verbose *.patch
        working-directory: vyos-build
      - name: Setup golang
        uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
        with:
          go-version: "1.26.5"
      - id: package_dir_commit
        name: Get package directory commit
        run: |
          if [[ '${{ matrix.package }}' == 'linux-kernel' ]]; then
            hash="$(git log -n 1 --format=%H -- 'data/defaults.toml' 'scripts/package-build/${{ matrix.package }}/')"
          else
            hash="$(git log -n 1 --format=%H -- 'scripts/package-build/${{ matrix.package }}/')"
          fi
          echo "commit=${hash}" >> "$GITHUB_OUTPUT"
        working-directory: vyos-build
      - id: cache
        name: Cache build
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          key: cache-${{ matrix.package }}-${{ matrix.arch }}-${{ steps.package_dir_commit.outputs.commit }}
          path: |
            vyos-build/scripts/package-build/**/*.deb
            vyos-build/scripts/package-build/**/*.buildinfo
            vyos-build/scripts/package-build/**/*.changes
            vyos-build/scripts/package-build/**/*.dsc
            vyos-build/scripts/package-build/**/*debian.tar.*
            vyos-build/scripts/package-build/**/*orig.tar.*
      - if: ${{ steps.cache.outputs.cache-hit != 'true' }}
        name: Build the package
        run: |
          python3 build.py
        working-directory: vyos-build/scripts/package-build/${{ matrix.package }}
      - name: List the .deb files built
        run: |
          ls -halp vyos-build/scripts/package-build/**/*.deb
      - name: Upload the .deb files as artifacts
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          if-no-files-found: error
          name: deb-${{ matrix.package }}-${{ matrix.arch }}
          path: |
            vyos-build/scripts/package-build/**/*.deb
      - name: Upload the remaining build files as artifacts
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: build-${{ matrix.package }}-${{ matrix.arch }}
          path: |
            vyos-build/scripts/package-build/**/*.buildinfo
            vyos-build/scripts/package-build/**/*.changes
            vyos-build/scripts/package-build/**/*.dsc
            vyos-build/scripts/package-build/**/*debian.tar.*
            vyos-build/scripts/package-build/**/*orig.tar.*
    strategy:
      fail-fast: false
      matrix:
        arch: [amd64, arm64]
        package:
          - amazon-cloudwatch-agent
          - amazon-ssm-agent
          - aws-gwlbtun
          - bash-completion
          - blackbox_exporter
          - ddclient
          - dropbear
          - ethtool
          - frr
          - frr_exporter
          - hostap
          - hsflowd
          - isc-dhcp
          - isc-kea
          - keepalived
          - libhtp
          - libnss-mapuser
          - libpam-radius-auth
          - linux-kernel
          - ndppd
          - net-snmp
          - netfilter
          - node_exporter
          - openvpn-otp
          - owamp
          - podman
          - pyhumps
          - radvd
          - squid
          - strongswan
          - tacacs
          - telegraf
          - udp-broadcast-relay
          # - unionfs-fuse
          - vyos-1x
          - waagent
          - wide-dhcpv6
          - xen-guest-agent
          - zerotier-one
        include:
          - arch: amd64
            runner_label: ubuntu-24.04
          - arch: arm64
            runner_label: ubuntu-24.04-arm
      max-parallel: 4
    timeout-minutes: 150
  build-extra:
    container:
      env:
        TZ: Australia/Brisbane
      image: ghcr.io/techbymatt/vyos-build:rolling@sha256:28cf2b26069f31998a6c031def5f4f1edf92b23c07f4cd40024c94f5452e7ad2
      options: "--privileged --sysctl net.ipv6.conf.lo.disable_ipv6=0"
    defaults:
      run:
        shell: bash
    name: Build (extra)
    permissions:
      packages: read
    runs-on: ${{ matrix.runner_label }}
    steps:
      - id: checkout
        name: Checkout the package repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          path: packages/${{ matrix.package }}
          ref: rolling
          repository: vyos/${{ matrix.package }}
      - if: ${{ matrix.deps }}
        name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install --yes ${{ matrix.deps }}
      - id: cache
        name: Cache build
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          key: cache-${{ matrix.package }}-${{ matrix.arch }}-${{ steps.checkout.outputs.commit }}
          path: |
            packages/*.deb
            packages/*.buildinfo
            packages/*.changes
            packages/*.dsc
            packages/*debian.tar.*
            packages/*orig.tar.*
      - if: ${{ steps.cache.outputs.cache-hit != 'true' }}
        name: Build the package
        run: |
          sudo apt-get update
          dpkg-buildpackage --build=binary --post-clean --unsigned-changes --unsigned-source
        working-directory: packages/${{ matrix.package }}
      - name: List the .deb files built
        run: |
          ls -halp packages/*.deb
      - name: Upload the .deb files as artifacts
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          if-no-files-found: error
          name: deb-${{ matrix.package }}-${{ matrix.arch }}
          path: |
            packages/*.deb
      - name: Upload the remaining build files as artifacts
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: build-${{ matrix.package }}-${{ matrix.arch }}
          path: |
            packages/*.buildinfo
            packages/*.changes
            packages/*.dsc
            packages/*debian.tar.*
            packages/*orig.tar.*
    strategy:
      fail-fast: false
      matrix:
        arch: [amd64, arm64]
        package:
          - hvinfo
          - ipaddrcheck
          - libnss-tacplus
          - libpam-tacplus
          - libtacplus-map
          - live-boot
          - vyatta-bash
          - vyatta-biosdevname
          - vyatta-cfg
          - vyos-http-api-tools
          - vyos-live-build
        include:
          - arch: amd64
            runner_label: ubuntu-24.04
          - arch: arm64
            runner_label: ubuntu-24.04-arm
          - deps: gnat gprbuild
            package: hvinfo
          - deps: check libcidr-dev
            package: ipaddrcheck
          - deps: libaudit-dev libpam-tacplus-dev libtac-dev libtacplus-map-dev
            package: libnss-tacplus
          - deps: autoconf-archive libaudit-dev libpam-dev libssl-dev libtacplus-map-dev
            package: libpam-tacplus
          - deps: autoconf-archive libaudit-dev
            package: libtacplus-map
          - deps: bison libncurses5-dev
            package: vyatta-bash
          - deps: libpci-dev
            package: vyatta-biosdevname
          - deps: bison flex libboost-filesystem-dev libglib2.0-dev
            package: vyatta-cfg
          - deps: dh-virtualenv
            package: vyos-http-api-tools
      max-parallel: 4
    timeout-minutes: 30
  publish:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    name: Publish
    needs:
      - build
      - build-extra
    permissions:
      id-token: write
      pages: write
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout the vyos-pkg repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: Download the .deb file artifacts
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          merge-multiple: true
          path: packages/rolling
          pattern: deb-*
      - name: Download the build file artifacts
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          merge-multiple: true
          path: packages/rolling
          pattern: build-*
      - name: Install required packages
        run: |
          sudo apt-get update
          sudo apt-get --no-install-recommends --yes install \
            jq \
            createrepo-c \
            coreutils \
            gnupg2 \
            dpkg-dev
      - name: Insert environment variables
        run: |
          {
            echo GNUPGHOME="$(mktemp -d /tmp/pgpkeys-XXXXXX)"
            echo REPO_OWNER="$(echo "${GITHUB_REPOSITORY}" | cut -d/ -f1)"
            echo REPO_NAME="$(echo "${GITHUB_REPOSITORY}" | cut -d/ -f2)"
          } >> "$GITHUB_ENV"
      - id: import_gpg
        name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@2dc316deee8e90f13e1a351ab510b4d5bc0c82cd # v7.0.0
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}
      - name: Confirm GPG key is loaded
        run: |
          gpg --list-keys | grep "${{ steps.import_gpg.outputs.fingerprint }}"
      - name: Setup Pages
        uses: actions/configure-pages@45bfe0192ca1faeb007ade9deae92b16b8254a0d # v6.0.0
      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@44a6e6beabd48582f863aeeb6cb2151cc1716697 # v1.0.13
      - name: Build .deb repository
        run: |
          export GPG_FINGERPRINT="${{ steps.import_gpg.outputs.fingerprint }}"
          export ORIGIN="${{ steps.import_gpg.outputs.name }}"
          sudo chown -R "$(whoami):$(whoami)" _site/
          scripts/build_repo.sh
      - name: Delete scripts/ repo
        run: |
          rm -r scripts
      - name: Generate directory indices
        uses: gacts/directory-listing@382b3439bf3a5787b20350780a0cc18553a47acd # v1.0.4
        with:
          show-hidden: true
          target: _site/deb
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@fc324d3547104276b827a68afc52ff2a11cc49c9 # v5.0.0
      - id: deployment
        name: Deploy to GitHub Pages
        uses: actions/deploy-pages@cd2ce8fcbc39b97be8ca5fce6e763baed58fa128 # v5.0.0
    timeout-minutes: 30
name: Repository
on:
  schedule:
    - cron: "42 19 */5 * *"
  workflow_dispatch:
permissions:
  contents: read
